#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the `wizard` skill.
#
# Everything above the STAGES marker is the wizard library and is identical in
# every wizard: do not hand-edit it. Author the per-step stages below it.

set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# Wizard library
# ─────────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Set by the author at the top of the STAGES section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WROTE_ENV=()     # KEYs upserted into ENV_FILE this run
WROTE_SECRET=()  # CI secret names set this run
PENDING=()       # things the wizard could not do — surfaced by finish()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
ok()   { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
bad()  { printf '  %s✗%s %s\n' "$RED" "$RESET" "$1"; }

# manual "description" — record something the human must do by hand. Always
# surfaces in the closing summary, so an un-automatable step is never silently
# dropped just because the wizard could not perform it.
manual() { PENDING+=("$1"); warn "by hand: $1"; }

# require CMD ["reason"] — assert a prerequisite tool exists. Missing tools are
# recorded rather than fatal: the human can still complete the browser work.
# Under `set -e` a bare `require foo` would exit on a miss, which defeats that —
# always call it as `if require foo; then …` or `require foo || true`.
require() {
  if command -v "$1" >/dev/null 2>&1; then
    return 0
  fi
  manual "install \`$1\`${2:+ — $2}"
  return 1
}

# banner "Title" — opening frame.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard says exactly what to do and captures\n' "$DIM"
  printf '  what you copy back. Ctrl-C any time and re-run later — values already\n'
  printf '  saved are offered back as defaults.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, announce the stage, show progress.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# open_url URL — open in the human's browser, cross-platform including WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open         >/dev/null 2>&1; then open "$url"
    else warn "no browser opener found — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "could not open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; succeeds on yes. Gate irreversible actions.
confirm() {
  local reply=""
  printf '  %s? %s%s [y/N] ' "$YELLOW" "$1" "$RESET"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line
  line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  [[ -n "$line" ]] || return 1
  printf '%s' "${line#*=}"
}

_prompt() {
  local prompt="$1" current="$2"
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
}

# ask KEY "Prompt" — read a visible value into $KEY, defaulting to what is
# already in ENV_FILE so re-runs are cheap.
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  _prompt "$prompt" "$current"
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — as ask, with hidden input.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  _prompt "$prompt" "$current"
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — idempotent upsert into ENV_FILE.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  # Re-writing a key on a later stage or a re-run must not double-count it in
  # the closing summary.
  case " ${WROTE_ENV[*]-} " in *" $key "*) ;; *) WROTE_ENV+=("$key") ;; esac
  ok "wrote $key → $ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret. Records a manual
# fallback rather than failing when gh is unavailable.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WROTE_SECRET+=("$name")
      ok "set CI secret $name"
      return 0
    fi
  fi
  manual "set CI secret $name (\`gh secret set $name\`)"
}

# set_var NAME VALUE — set a non-secret GitHub Actions repo variable.
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      ok "set CI variable $name"
      return 0
    fi
  fi
  manual "set CI variable $name (\`gh variable set $name\`)"
}

# check "description" <command...> — verify a manual step actually took effect.
# On failure the human may retry (they just changed something) or skip, in which
# case it lands in the closing summary. A step with an observable result is a
# step the human cannot silently get wrong.
#
# Always returns 0: a skipped check is a recorded outcome, not a script failure,
# and returning non-zero under `set -e` would abort the run mid-procedure —
# stranding the human halfway through with no summary.
check() {
  local description="$1"; shift
  while true; do
    printf '  %s⋯%s checking %s\n' "$DIM" "$RESET" "$description"
    if "$@" >/dev/null 2>&1; then
      ok "$description"
      return 0
    fi
    bad "$description — not yet"
    if confirm "Retry the check?"; then
      continue
    fi
    manual "verify: $description"
    return 0
  done
}

# await "description" <command...> — poll until a command succeeds, for changes
# that propagate (DNS, certificate issuance, deploys). Honours WAIT_TRIES and
# WAIT_SECONDS; falls through to check()'s retry/skip prompt when it gives up.
await() {
  local description="$1"; shift
  local tries="${WAIT_TRIES:-20}" gap="${WAIT_SECONDS:-15}" i=1
  printf '  %s⋯%s waiting for %s %s(up to %s min)%s\n' \
    "$DIM" "$RESET" "$description" "$DIM" "$(( tries * gap / 60 ))" "$RESET"
  while (( i <= tries )); do
    if "$@" >/dev/null 2>&1; then
      ok "$description"
      return 0
    fi
    printf '  %s  attempt %s/%s — retrying in %ss%s\r' "$DIM" "$i" "$tries" "$gap" "$RESET"
    sleep "$gap"
    (( i++ ))
  done
  printf '\n'
  bad "$description — still not visible after $(( tries * gap / 60 )) min"
  note "propagation can take longer; this is not necessarily an error"
  check "$description" "$@"
}

# finish — closing summary. Everything recorded by manual() surfaces here.
finish() {
  _clear
  printf '\n%s%s  ✓ Done%s\n\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WROTE_ENV[@]} ))    && note "wrote ${#WROTE_ENV[@]} value(s) to $ENV_FILE: ${WROTE_ENV[*]}"
  (( ${#WROTE_SECRET[@]} )) && note "set ${#WROTE_SECRET[@]} CI secret(s): ${WROTE_SECRET[*]}"
  if (( ${#PENDING[@]} )); then
    printf '\n'
    warn "still to do by hand:"
    local item
    for item in "${PENDING[@]}"; do note "  - $item"; done
  fi
  printf '\n'
}

# ─────────────────────────────────────────────────────────────────────────────
# STAGES — author below. One stage() per step the human takes.
# Replace the example. Set the totals to match the stages you write.
# ─────────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
TOTAL_MINUTES=100

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
PROTOTYPE_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
REPOSITORY_ROOT=$(cd "$PROTOTYPE_ROOT/../.." && pwd)
EXPECTED_BRANCH="prototype/48-render-cadence"
APPROVED_NAME="Developer ID Application: TIMOTHY G HARRIS (F66FM4V88Q)"
APPROVED_TEAM="F66FM4V88Q"
APPROVED_SHA1="189EC9780DE0A94CF5B24CC5983CAB3FDAE15638"
BUNDLE_ID="dev.clickai.grabrabbit.prototype.render-cadence"
STABLE_APP_DIR="$PROTOTYPE_ROOT/.build/human-gate-stable"
STABLE_APP="$STABLE_APP_DIR/Grab Rabbit Live Cadence Probe.app"
STAGING_MANIFEST="$STABLE_APP_DIR/staging-manifest.json"
LIVE_PROBE="$STABLE_APP/Contents/MacOS/live-cadence-probe"
UNSIGNED_PROBE="$PROTOTYPE_ROOT/.build/release/live-cadence-probe"
RUN_SHA=$(git -C "$REPOSITORY_ROOT" rev-parse HEAD 2>/dev/null || true)
RUN_STAMP=$(date -u +%Y%m%dT%H%M%SZ)
EVIDENCE_DIR="$PROTOTYPE_ROOT/evidence/human-gate-${RUN_SHA:0:7}-$RUN_STAMP"
RUNS_DIR="$EVIDENCE_DIR/runs"
PROCESS_LEDGER="$EVIDENCE_DIR/processes.tsv"
ENV_FILE=/dev/null
WIZARD_OWNED_PIDS=()
CAMERA_WAS_PRESENT_INITIALLY=false
CAMERA_ID=""
WINDOW_ID=""
SELECTED_CAMERA_NAME=""
SELECTED_CAMERA_TYPE=""
SELECTED_WINDOW_APP=""
LAST_RUN_FAILURE=""
CAMERA_STATE_MAY_DIFFER=false
STABLE_APP_MAY_EXIST=false
CREATED_STABLE_APP_DIR=""
TCC_STATE_MAY_DIFFER=false
BROWSER_CASE_MAY_BE_OPEN=false
TCC_BEFORE_FILE="$EVIDENCE_DIR/tcc-before.json"
TCC_AFTER_FILE="$EVIDENCE_DIR/tcc-after.json"
VOLUME_BEFORE_FILE="$EVIDENCE_DIR/volume-before.txt"
POWER_BEFORE_FILE="$EVIDENCE_DIR/power-before.txt"
CUA_DRIVER_PATH="/Applications/CuaDriver.app/Contents/MacOS/cua-driver"
SCREENSHARINGD_PATH="/System/Library/CoreServices/RemoteManagement/screensharingd.bundle/Contents/MacOS/screensharingd"

owned_pid_is_running() {
  local target="$1" pid running
  running=$(jobs -pr)
  for pid in $running; do
    [[ "$pid" == "$target" ]] && return 0
  done
  return 1
}

cleanup_owned_processes() {
  local pid
  for pid in "${WIZARD_OWNED_PIDS[@]-}"; do
    [[ -n "$pid" ]] || continue
    if [[ "$pid" == "12083" || "$pid" == "9243" ]]; then
      continue
    fi
    if owned_pid_is_running "$pid" && kill -0 "$pid" >/dev/null 2>&1; then
      kill -INT "$pid" >/dev/null 2>&1 || true
      wait "$pid" >/dev/null 2>&1 || true
    fi
  done
  WIZARD_OWNED_PIDS=()
}

untrack_owned_pid() {
  local target="$1" pid
  local remaining=()
  for pid in "${WIZARD_OWNED_PIDS[@]-}"; do
    [[ -n "$pid" && "$pid" != "$target" ]] && remaining+=("$pid")
  done
  if (( ${#remaining[@]} )); then
    WIZARD_OWNED_PIDS=("${remaining[@]}")
  else
    WIZARD_OWNED_PIDS=()
  fi
}

stable_app_directory_is_empty() {
  local directory="$1" entry
  [[ -d "$directory" && ! -L "$directory" ]] || return 1
  for entry in "$directory"/* "$directory"/.[!.]* "$directory"/..?*; do
    [[ ! -e "$entry" && ! -L "$entry" ]] || return 1
  done
}

record_pending_restoration() {
  [[ "$TCC_STATE_MAY_DIFFER" == false ]] \
    || manual "restore the prototype bundle's Camera, Microphone, and Screen Capture TCC state to $TCC_BEFORE_FILE"
  [[ "$STABLE_APP_MAY_EXIST" == false ]] \
    || manual "move only the manifest-verified staged probe and staging manifest in $STABLE_APP_DIR to Trash after its processes stop"
  [[ -z "$CREATED_STABLE_APP_DIR" ]] \
    || manual "after moving the two verified staged artifacts to Trash, remove only the recorded helper-created directory $CREATED_STABLE_APP_DIR if it is empty and still equals $PROTOTYPE_ROOT/.build/human-gate-stable"
  [[ "$CAMERA_STATE_MAY_DIFFER" == false ]] \
    || manual "restore the physical camera inventory to its before-run state"
  [[ "$BROWSER_CASE_MAY_BE_OPEN" == false ]] \
    || manual "close the wizard-created browser-case page"
}

on_interrupt() {
  cleanup_owned_processes
  manual "resume the interrupted wizard and complete every remaining physical, TCC, resource, and visual step"
  record_pending_restoration
  finish
  exit 130
}

trap cleanup_owned_processes EXIT
trap on_interrupt INT TERM

fatal_gate() {
  bad "$1"
  manual "$1"
  record_pending_restoration
  finish
  exit 1
}

required_tool() {
  if ! require "$1" "$2"; then
    fatal_gate "install $1 before running this gate"
  fi
}

required_check() {
  local description="$1"; shift
  check "$description" "$@"
  if ! "$@" >/dev/null 2>&1; then
    fatal_gate "$description"
  fi
}

camera_id_is_present() {
  "$UNSIGNED_PROBE" list-sources --skip-window-query \
    | jq -e --arg camera_id "$CAMERA_ID" '.cameras | any(.uniqueID == $camera_id)' >/dev/null
}

signed_camera_id_is_present() {
  "$LIVE_PROBE" list-sources --skip-window-query \
    | jq -e --arg camera_id "$CAMERA_ID" '.cameras | any(.uniqueID == $camera_id)' >/dev/null
}

window_id_is_present() {
  "$LIVE_PROBE" list-sources \
    | jq -e --argjson window_id "$WINDOW_ID" '.windows | any(.windowID == $window_id)' >/dev/null
}

signed_probe_identity_is_approved() {
  [[ -x "$LIVE_PROBE" ]] || return 1
  "$LIVE_PROBE" list-sources --skip-window-query \
    | jq -e --arg sha "$APPROVED_SHA1" --arg team "$APPROVED_TEAM" \
      '.signing.approvedDeveloperIDPresent == true
       and .signing.teamIdentifier == $team
       and (.signing.certificateSHA1s | index($sha) != null)' >/dev/null
}

staged_app_manifest_is_exact() {
  local info_sha executable_sha details actual_name actual_team actual_bundle certificate_dir actual_sha
  [[ "$PROTOTYPE_ROOT" == /* ]] || return 1
  [[ "$STABLE_APP_DIR" == "$PROTOTYPE_ROOT/.build/human-gate-stable" ]] || return 1
  [[ "$STABLE_APP" == "$STABLE_APP_DIR/Grab Rabbit Live Cadence Probe.app" ]] || return 1
  [[ "$STAGING_MANIFEST" == "$STABLE_APP_DIR/staging-manifest.json" ]] || return 1
  [[ -d "$STABLE_APP_DIR" && ! -L "$STABLE_APP_DIR" ]] || return 1
  [[ -d "$STABLE_APP" && ! -L "$STABLE_APP" ]] || return 1
  [[ -f "$STAGING_MANIFEST" && ! -L "$STAGING_MANIFEST" ]] || return 1
  [[ "$(find "$STABLE_APP_DIR" -mindepth 1 -maxdepth 1 | wc -l | tr -d ' ')" -eq 2 ]] || return 1
  [[ "$(find "$STABLE_APP" -type l | wc -l | tr -d ' ')" -eq 0 ]] || return 1
  info_sha=$(shasum -a 256 "$STABLE_APP/Contents/Info.plist" | awk '{print $1}') || return 1
  executable_sha=$(shasum -a 256 "$LIVE_PROBE" | awk '{print $1}') || return 1
  jq -e --arg branch "$EXPECTED_BRANCH" --arg sha "$RUN_SHA" --arg directory "$STABLE_APP_DIR" \
      --arg info "$info_sha" --arg executable "$executable_sha" --arg bundle "$BUNDLE_ID" \
      --arg name "$APPROVED_NAME" --arg team "$APPROVED_TEAM" --arg fingerprint "$APPROVED_SHA1" '
      .schema == "grab-rabbit-render-cadence-staged-app-v1" and .branch == $branch and .git_sha == $sha
      and .remote_directory == $directory and .app_relative_path == "Grab Rabbit Live Cadence Probe.app"
      and .hashes.info_plist_sha256 == $info and .hashes.executable_sha256 == $executable
      and .signing.bundle_id == $bundle and .signing.common_name == $name
      and .signing.team_id == $team and .signing.certificate_sha1 == $fingerprint
      and .signing.hardened_runtime == true and .cleanup_owner == "human-gate-wizard"' \
      "$STAGING_MANIFEST" >/dev/null || return 1
  codesign --verify --deep --strict --verbose=2 "$STABLE_APP" || return 1
  details=$(codesign -dvvv "$STABLE_APP" 2>&1) || return 1
  actual_name=$(sed -n 's/^Authority=//p' <<<"$details" | head -1)
  actual_team=$(sed -n 's/^TeamIdentifier=//p' <<<"$details" | head -1)
  grep -Eq '^CodeDirectory .* flags=.*\(runtime\)' <<<"$details" || return 1
  actual_bundle=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$STABLE_APP/Contents/Info.plist") || return 1
  [[ "$actual_name" == "$APPROVED_NAME" && "$actual_team" == "$APPROVED_TEAM" \
      && "$actual_bundle" == "$BUNDLE_ID" ]] || return 1
  certificate_dir=$(mktemp -d /tmp/grab-rabbit-48-wizard-cert.XXXXXX) || return 1
  if ! codesign -d --extract-certificates="$certificate_dir/cert-" "$STABLE_APP"; then
    rm -rf "$certificate_dir"
    return 1
  fi
  actual_sha=$(openssl x509 -inform DER -in "$certificate_dir/cert-0" -noout -fingerprint -sha1 \
      | cut -d= -f2 | tr -d ':')
  rm -rf "$certificate_dir"
  [[ "$actual_sha" == "$APPROVED_SHA1" ]]
}

tcc_is_granted() {
  "$LIVE_PROBE" list-sources --skip-window-query \
    | jq -e '.authorization.camera == "authorized"
             and .authorization.microphone == "authorized"
             and .authorization.screenCapturePreflightGranted == true' >/dev/null
}

exact_preflight_passes_without_output() {
  local forbidden="$EVIDENCE_DIR/preflight-must-not-exist.mov"
  [[ ! -e "$forbidden" ]] || return 1
  "$LIVE_PROBE" preflight \
    --camera-id "$CAMERA_ID" \
    --window-id "$WINDOW_ID" \
    --output "$forbidden" >/dev/null 2>&1 \
    && [[ ! -e "$forbidden" ]]
}

log_process() {
  printf '%s\t%s\t%s\t%s\t%s\n' "$1" "$2" "$3" "$4" "$5" >>"$PROCESS_LEDGER"
}

validate_live_run() {
  local movie="$1" metrics="$2" events="$3" expected_disconnect="$4"
  [[ -s "$movie" && -s "$metrics" && -s "$events" ]] || return 1
  ffprobe -v error \
    -show_entries stream=codec_name,codec_type,duration:format=duration \
    -of json "$movie" \
    | jq -e '
        ([.streams[] | select(.codec_type == "video" and .codec_name == "h264")] | length) == 1
        and ([.streams[] | select(.codec_type == "audio" and .codec_name == "aac")] | length) >= 1
        and (.format.duration | tonumber) > 0' >/dev/null \
    || return 1
  jq -e --argjson expected_disconnect "$expected_disconnect" \
      --arg approved_sha "$APPROVED_SHA1" --arg approved_team "$APPROVED_TEAM" '
      .videoFramesAppended > 0
      and .videoAppendFailures == 0
      and .monotonicTimestamps == true
      and .privacySentinelPixelsAtCacheIngress == 0
      and .privacySentinelPixelsRendered == 0
      and .privacyUnsanitizedExteriorPixelsAtCacheIngress == 0
      and .signing.approvedDeveloperIDPresent == true
      and .signing.teamIdentifier == $approved_team
      and (.signing.certificateSHA1s | index($approved_sha) != null)
      and .authorizationBefore.camera == "authorized"
      and .authorizationBefore.microphone == "authorized"
      and .authorizationAfter.camera == "authorized"
      and .authorizationAfter.microphone == "authorized"
      and .selectedCamera.exactUniqueIDMatchedInProcess == true
      and ((.selectedWindow == null) or .selectedWindow.exactWindowIDMatchedInProcess == true)
      and ((.selectedWindow == null)
           or (.authorizationBefore.screenCapturePreflightGranted == true
               and .authorizationAfter.screenCapturePreflightGranted == true))
      and .selectedCameraDisconnected == $expected_disconnect
      and (if $expected_disconnect
           then .stopReason == "selected-camera-disconnected"
           else .stopReason == "duration-complete" and .pauseCount == 1 and .resumeCount == 1
           end)' "$metrics" >/dev/null
}

run_owned_record_no_confirm() {
  local stem="$1" expected_disconnect="$2" started stopped code pid
  shift 2
  local movie="$RUNS_DIR/$stem.mov"
  local metrics="$RUNS_DIR/$stem.metrics.json"
  local events="$RUNS_DIR/$stem.events.jsonl"
  local stdout="$RUNS_DIR/$stem.stdout.json"
  local stderr="$RUNS_DIR/$stem.stderr.txt"
  LAST_RUN_FAILURE=""
  [[ ! -e "$movie" && ! -e "$metrics" && ! -e "$events" && ! -e "$stdout" && ! -e "$stderr" ]] \
    || { LAST_RUN_FAILURE="refusing to overwrite evidence for $stem"; return 1; }
  started=$(date -u +%Y-%m-%dT%H:%M:%SZ) \
    || { LAST_RUN_FAILURE="could not timestamp $stem"; return 1; }
  "$LIVE_PROBE" record "$@" \
    --output "$movie" \
    --metrics "$metrics" \
    --events "$events" \
    >"$stdout" 2>"$stderr" &
  pid=$!
  WIZARD_OWNED_PIDS+=("$pid")
  if wait "$pid"; then code=0; else code=$?; fi
  untrack_owned_pid "$pid"
  stopped=$(date -u +%Y-%m-%dT%H:%M:%SZ) \
    || { LAST_RUN_FAILURE="could not timestamp the end of $stem"; return 1; }
  log_process "$pid" "$stem" "$started" "$stopped" "$code" \
    || { LAST_RUN_FAILURE="could not update the process ledger for $stem"; return 1; }
  if [[ "$code" -ne 0 ]]; then
    LAST_RUN_FAILURE="$stem exited $code; inspect its redacted stderr evidence"
    return 1
  fi
  if ! validate_live_run "$movie" "$metrics" "$events" "$expected_disconnect"; then
    LAST_RUN_FAILURE="$stem failed playability, cadence, signer, disconnect, or privacy validation"
    return 1
  fi
  return 0
}

run_owned_record() {
  local stem="$1" expected_disconnect="$2"
  shift 2
  if ! confirm "Create and record the non-overwriting evidence run '$stem' now?"; then
    fatal_gate "run $stem was not authorized"
  fi
  if ! run_owned_record_no_confirm "$stem" "$expected_disconnect" "$@"; then
    fatal_gate "$LAST_RUN_FAILURE"
  fi
  required_check "$stem is playable, monotonic, approved-signed, and privacy-clean" \
    validate_live_run "$RUNS_DIR/$stem.mov" "$RUNS_DIR/$stem.metrics.json" "$RUNS_DIR/$stem.events.jsonl" "$expected_disconnect"
}

run_disconnect_record() {
  local candidate="$1" stem="disconnect-$1" started stopped code pid
  local movie="$RUNS_DIR/$stem.mov"
  local metrics="$RUNS_DIR/$stem.metrics.json"
  local events="$RUNS_DIR/$stem.events.jsonl"
  local stdout="$RUNS_DIR/$stem.stdout.json"
  local stderr="$RUNS_DIR/$stem.stderr.txt"
  [[ ! -e "$movie" && ! -e "$metrics" && ! -e "$events" && ! -e "$stdout" && ! -e "$stderr" ]] \
    || fatal_gate "refusing to overwrite evidence for $stem"
  if ! confirm "Start the $candidate physical-disconnect run? You will unplug only the selected camera when prompted."; then
    fatal_gate "$candidate physical-disconnect run was not authorized"
  fi
  started=$(date -u +%Y-%m-%dT%H:%M:%SZ) || fatal_gate "could not timestamp $stem"
  "$LIVE_PROBE" record \
    --camera-id "$CAMERA_ID" --window-id "$WINDOW_ID" \
    --candidate "$candidate" --canvas 16x9 --duration 60 --fps 30 \
    --pause-at 4 --pause-duration 1 --system-audio --microphone \
    --output "$movie" --metrics "$metrics" --events "$events" \
    >"$stdout" 2>"$stderr" &
  pid=$!
  WIZARD_OWNED_PIDS+=("$pid")
  sleep 3
  if ! owned_pid_is_running "$pid"; then
    if wait "$pid"; then code=0; else code=$?; fi
    untrack_owned_pid "$pid"
    stopped=$(date -u +%Y-%m-%dT%H:%M:%SZ) || stopped="timestamp-unavailable"
    log_process "$pid" "$stem" "$started" "$stopped" "$code" || true
    fatal_gate "$stem stopped before the physical-disconnect prompt (exit $code)"
  fi
  say "The exact selected camera is recording. Do not disconnect Screen Sharing or any other device."
  if ! confirm "Physically disconnect only the selected camera now?"; then
    if owned_pid_is_running "$pid"; then kill -INT "$pid" >/dev/null 2>&1 || true; fi
    if wait "$pid"; then code=0; else code=$?; fi
    untrack_owned_pid "$pid"
    stopped=$(date -u +%Y-%m-%dT%H:%M:%SZ) || stopped="timestamp-unavailable"
    log_process "$pid" "$stem" "$started" "$stopped" "$code" || true
    fatal_gate "$candidate physical disconnect was not performed"
  fi
  pause "Disconnect it, wait for the probe to stop visibly, then press Enter."
  if wait "$pid"; then code=0; else code=$?; fi
  untrack_owned_pid "$pid"
  stopped=$(date -u +%Y-%m-%dT%H:%M:%SZ) || fatal_gate "could not timestamp the end of $stem"
  log_process "$pid" "$stem" "$started" "$stopped" "$code" \
    || fatal_gate "could not update the process ledger for $stem"
  [[ "$code" -eq 0 ]] || fatal_gate "$stem exited $code"
  required_check "$stem stopped for the exact selected-camera disconnect and remained playable/privacy-clean" \
    validate_live_run "$movie" "$metrics" "$events" true
  say "Reconnect the same physical camera. The wizard will refuse a different device."
  pause "Wait until macOS shows the camera as available, then press Enter."
  required_check "the same stable camera ID returned after reconnect" signed_camera_id_is_present
}

verify_all_outputs() {
  local movie metrics events expected_disconnect count=0
  local movies=("$RUNS_DIR"/*.mov)
  [[ -f "${movies[0]}" ]] || return 1
  for movie in "${movies[@]}"; do
    metrics="${movie%.mov}.metrics.json"
    events="${movie%.mov}.events.jsonl"
    [[ -s "$metrics" && -s "$events" ]] || return 1
    case "${movie##*/}" in
      disconnect-*) expected_disconnect=true ;;
      *) expected_disconnect=false ;;
    esac
    validate_live_run "$movie" "$metrics" "$events" "$expected_disconnect" || return 1
    count=$((count + 1))
  done
  [[ "$count" -eq 28 ]]
}

no_owned_process_is_live() {
  local pid
  for pid in "${WIZARD_OWNED_PIDS[@]-}"; do
    [[ -n "$pid" ]] || continue
    if owned_pid_is_running "$pid"; then return 1; fi
  done
  return 0
}

protected_processes_are_live() {
  protected_process_has_exact_path 12083 "$CUA_DRIVER_PATH" \
    && protected_process_has_exact_path 9243 "$SCREENSHARINGD_PATH"
}

protected_process_has_exact_path() {
  local pid="$1" expected_path="$2" actual_path
  actual_path=$(ps -ww -p "$pid" -o comm=) || return 1
  actual_path=${actual_path#"${actual_path%%[![:space:]]*}"}
  actual_path=${actual_path%"${actual_path##*[![:space:]]}"}
  [[ "$actual_path" == "$expected_path" ]]
}

tcc_matches_snapshot() {
  jq -s -e '
    .[0].authorization.camera == .[1].authorization.camera
    and .[0].authorization.microphone == .[1].authorization.microphone
    and .[0].authorization.screenCapturePreflightGranted == .[1].authorization.screenCapturePreflightGranted' \
    "$TCC_BEFORE_FILE" "$TCC_AFTER_FILE" >/dev/null
}

branch_is_expected() {
  local branch
  branch=$(git -C "$REPOSITORY_ROOT" branch --show-current) || return 1
  [[ "$branch" == "$EXPECTED_BRANCH" ]]
}

checkout_is_clean() {
  local status
  status=$(git -C "$REPOSITORY_ROOT" status --porcelain) || return 1
  [[ -z "$status" ]]
}

head_is_pushed() {
  local remote
  remote=$(git -C "$REPOSITORY_ROOT" rev-parse origin/prototype/48-render-cadence) || return 1
  [[ "$RUN_SHA" == "$remote" ]]
}

host_is_mac_mini() {
  system_profiler SPHardwareDataType | grep -F 'Model Name: Mac mini' >/dev/null
}

camera_count_is_positive() {
  jq -e '.cameras | length > 0' <<<"$SOURCE_JSON" >/dev/null
}

window_id_is_valid_number() {
  jq -ne --arg id "$WINDOW_ID" \
    '($id | test("^[1-9][0-9]*$")) and (($id | tonumber) <= 4294967295)' >/dev/null
}

movie_count_is() {
  local expected="$1" count
  local movies=("$RUNS_DIR"/*.mov)
  if [[ ! -f "${movies[0]}" ]]; then count=0; else count=${#movies[@]}; fi
  [[ "$count" -eq "$expected" ]]
}

powermetrics_bindings_are_valid() {
  jq -e '.metrics_sha256 and .powermetrics_sha256' \
    "$EVIDENCE_DIR/power-camera-driven.binding.json" >/dev/null \
    && jq -e '.metrics_sha256 and .powermetrics_sha256' \
      "$EVIDENCE_DIR/power-fixed-clock.binding.json" >/dev/null
}

selected_camera_is_absent() {
  local inventory code
  inventory=$("$UNSIGNED_PROBE" list-sources --skip-window-query) || return 1
  if jq -e --arg camera_id "$CAMERA_ID" '.cameras | any(.uniqueID == $camera_id)' \
      <<<"$inventory" >/dev/null; then
    return 1
  else
    code=$?
  fi
  [[ "$code" -eq 1 ]]
}

camera_inventory_matches_initial() {
  local inventory
  inventory=$("$UNSIGNED_PROBE" list-sources --skip-window-query) || return 1
  printf '%s\n%s\n' "$INITIAL_SOURCE_JSON" "$inventory" | jq -s -e '
    ([.[0].cameras[] | {uniqueID, name, deviceType}] | sort_by(.uniqueID))
    == ([.[1].cameras[] | {uniqueID, name, deviceType}] | sort_by(.uniqueID))' >/dev/null
}

camera_identifier_is_not_persisted() {
  local code
  if rg -a -F -- "$CAMERA_ID" "$EVIDENCE_DIR" >/dev/null 2>&1; then
    return 1
  else
    code=$?
  fi
  [[ "$code" -eq 1 ]]
}

identifier_fields_are_not_persisted() {
  local code
  if rg -a '"(uniqueID|windowID|cameraID|camera_id|window_id)"[[:space:]]*:|Invalid --window-id:|--(camera|window)-id' \
      "$EVIDENCE_DIR" >/dev/null 2>&1; then
    return 1
  else
    code=$?
  fi
  [[ "$code" -eq 1 ]]
}

verdict_reason_has_no_exact_identifier() {
  local reason
  reason=$(jq -r '.reason' "$EVIDENCE_DIR/verdict.json") || return 1
  [[ "$reason" != *"$CAMERA_ID"* && "$reason" != *"$WINDOW_ID"* ]]
}

verdict_is_valid() {
  case "$VERDICT" in
    camera-driven|fixed-clock|unresolved) return 0 ;;
    *) return 1 ;;
  esac
}

evidence_hashes_verify() {
  (cd "$EVIDENCE_DIR" && shasum -a 256 -c SHA256SUMS)
}

checkout_remains_bound() {
  local status head remote
  status=$(git -C "$REPOSITORY_ROOT" status --porcelain) || return 1
  head=$(git -C "$REPOSITORY_ROOT" rev-parse HEAD) || return 1
  remote=$(git -C "$REPOSITORY_ROOT" rev-parse origin/prototype/48-render-cadence) || return 1
  [[ -z "$status" && "$RUN_SHA" == "$head" && "$RUN_SHA" == "$remote" ]]
}

wait_for_powermetrics_output() {
  local waited=0
  LAST_RUN_FAILURE=""
  while [[ ! -s "$POWER_FILE" ]]; do
    if [[ -e "$POWER_DONE_FILE" ]]; then
      LAST_RUN_FAILURE="powermetrics ended before producing sampler output"
      return 1
    fi
    if [[ "$waited" -ge 120 ]]; then
      LAST_RUN_FAILURE="powermetrics produced no sampler output within two minutes"
      return 1
    fi
    sleep 1
    waited=$((waited + 1))
  done
}

run_performance_pair() {
  trap 'cleanup_owned_processes; exit 130' INT TERM
  trap cleanup_owned_processes EXIT
  if ! wait_for_powermetrics_output; then
    printf '%s\n' "$LAST_RUN_FAILURE" >"$PERF_ERROR_FILE" || true
    return 1
  fi
  if ! run_owned_record_no_confirm "power-camera-driven" false \
      --camera-id "$CAMERA_ID" --window-id "$WINDOW_ID" \
      --candidate camera-driven --canvas square --duration 20 --fps 30 \
      --pause-at 8 --pause-duration 1 --system-audio --microphone \
      --powermetrics-path "$POWER_FILE"; then
    printf '%s\n' "$LAST_RUN_FAILURE" >"$PERF_ERROR_FILE" || true
    return 1
  fi
  if ! run_owned_record_no_confirm "power-fixed-clock" false \
      --camera-id "$CAMERA_ID" --window-id "$WINDOW_ID" \
      --candidate fixed-clock --canvas square --duration 20 --fps 30 \
      --pause-at 8 --pause-duration 1 --system-audio --microphone \
      --powermetrics-path "$POWER_FILE"; then
    printf '%s\n' "$LAST_RUN_FAILURE" >"$PERF_ERROR_FILE" || true
    return 1
  fi
}

banner "Grab Rabbit render-cadence human gate"

stage "Connect and verify the exact camera" 10
say "What and why: Studio must bind one physical camera by its stable device ID and must never switch silently. This stage builds only the unsigned inventory tool, then keeps your chosen ID in this shell process—not in .env or evidence."
required_tool git "the repository/SHA guard"
required_tool swift "the live probe build"
required_tool jq "machine-readable checks"
required_tool rg "exact-identifier evidence scan"
required_tool ffprobe "playable-output checks"
required_tool codesign "signed-app verification"
required_tool openssl "certificate fingerprint verification"
required_tool powermetrics "CPU/GPU/ANE/thermal sampling"
required_tool sudo "direct administrator-owned powermetrics prompt"
required_tool tccutil "exact prototype-bundle TCC restoration"
required_tool osascript "volume snapshot and Finder trash restoration"
required_check "this is the assigned prototype branch" branch_is_expected
required_check "the checkout is clean before evidence begins" checkout_is_clean
required_check "HEAD is bound to the pushed prototype branch" head_is_pushed
required_check "this host is a Mac mini" host_is_mac_mini
required_check "protected CuaDriver PID 12083 and Screen Sharing PID 9243 are live" protected_processes_are_live
if ! confirm "Create the dedicated ignored evidence directory, snapshot read-only host state, and build the unsigned inventory probe?"; then
  fatal_gate "evidence initialization was not authorized"
fi
[[ ! -e "$EVIDENCE_DIR" ]] || fatal_gate "refusing to overwrite evidence directory $EVIDENCE_DIR"
umask 077
mkdir -p "$RUNS_DIR" || fatal_gate "could not create the ignored evidence directory"
printf 'pid\trun\tstarted_utc\tstopped_utc\texit_code\n' >"$PROCESS_LEDGER" \
  || fatal_gate "could not initialize the process ledger"
osascript -e 'get volume settings' >"$VOLUME_BEFORE_FILE" \
  || fatal_gate "could not snapshot audio volume/mute state"
pmset -g custom >"$POWER_BEFORE_FILE" \
  || fatal_gate "could not snapshot power preferences"
ps -p 12083,9243 -o pid=,comm=,etime= >"$EVIDENCE_DIR/protected-before.txt" \
  || fatal_gate "could not snapshot the protected processes"
sw_vers >"$EVIDENCE_DIR/os.txt" || fatal_gate "could not snapshot macOS version"
system_profiler SPHardwareDataType -json >"$EVIDENCE_DIR/hardware.json" \
  || fatal_gate "could not snapshot Mini hardware"
swift build --package-path "$PROTOTYPE_ROOT" -c release -Xswiftc -warnings-as-errors \
  >"$EVIDENCE_DIR/unsigned-build.log" 2>&1 \
  || fatal_gate "the unsigned inventory probe did not compile; inspect unsigned-build.log"
required_check "the unsigned inventory probe compiled" test -x "$UNSIGNED_PROBE"
INITIAL_SOURCE_JSON=$("$UNSIGNED_PROBE" list-sources --skip-window-query) \
  || fatal_gate "the unsigned probe could not read the initial camera inventory"
jq -e '.cameras | type == "array"' <<<"$INITIAL_SOURCE_JSON" >/dev/null \
  || fatal_gate "the initial camera inventory was not valid JSON"
if ! confirm "Open Apple's Continuity Camera setup article before connecting the camera?"; then
  fatal_gate "primary-source camera setup was not reviewed"
fi
open_url "https://support.apple.com/en-us/102546"
step "For iPhone: on the iPhone, open Settings → General → AirPlay & Continuity (or AirPlay & Handoff), and make sure Continuity Camera is on. Apple documents this exact path."
step "Make sure the iPhone and Mini use the same two-factor-authenticated Apple Account, are near each other, and have Bluetooth and Wi-Fi on. For USB, unlock the iPhone and accept Trust if macOS asks."
step "Mount the iPhone stably with its rear cameras unobstructed, or connect the other real camera. Do not use Screen Sharing as a camera."
CAMERA_STATE_MAY_DIFFER=true
pause "Connect the camera and wait for macOS to finish discovering it, then press Enter."
SOURCE_JSON=$("$UNSIGNED_PROBE" list-sources --skip-window-query) \
  || fatal_gate "the unsigned probe could not read the connected camera inventory"
jq -r '.cameras[] | "  Camera: \(.name) [\(.deviceType)]\n  Stable ID: \(.uniqueID)"' <<<"$SOURCE_JSON" \
  || fatal_gate "the connected camera inventory was not valid JSON"
required_check "at least one real camera is enumerated" camera_count_is_positive
ask CAMERA_ID "Paste the exact Stable ID shown for the camera you will physically use:"
[[ -n "$CAMERA_ID" ]] || fatal_gate "an exact camera ID is required"
required_check "the exact selected camera ID is present with no substitution" camera_id_is_present
if jq -e --arg camera_id "$CAMERA_ID" '.cameras | any(.uniqueID == $camera_id)' \
    <<<"$INITIAL_SOURCE_JSON" >/dev/null; then
  CAMERA_WAS_PRESENT_INITIALLY=true
else
  INITIAL_SELECTION_EXIT=$?
  [[ "$INITIAL_SELECTION_EXIT" -eq 1 ]] \
    || fatal_gate "the initial camera inventory could not be compared with the selected camera"
fi
SELECTED_CAMERA_NAME=$(jq -er --arg camera_id "$CAMERA_ID" \
  '.cameras[] | select(.uniqueID == $camera_id) | .name' <<<"$SOURCE_JSON") \
  || fatal_gate "the selected camera name could not be read"
SELECTED_CAMERA_TYPE=$(jq -er --arg camera_id "$CAMERA_ID" \
  '.cameras[] | select(.uniqueID == $camera_id) | .deviceType' <<<"$SOURCE_JSON") \
  || fatal_gate "the selected camera type could not be read"
ok "Selected $SELECTED_CAMERA_NAME ($SELECTED_CAMERA_TYPE); its ID remains only in this wizard process."

stage "Verify and visibly authorize the staged stable probe" 15
say "What and why: TCC grants bind to one stable signed identity and path. A laptop with the approved signer must already have staged this exact-SHA app and manifest. The Mini only verifies the artifact; it never signs or handles signing credentials, so unrelated Mini identities do not affect this gate."
step "Before this wizard starts, run scripts/stage-signed-app-to-mini.sh with this exact 40-character SHA on the approved-signing laptop: $RUN_SHA"
step "That helper refuses a dirty, moved, or unpushed branch and refuses any existing or unexpected Mini target. If staging is absent or partial, stop and resolve it on the laptop; do not modify the stable directory by hand."
[[ -e "$STABLE_APP_DIR" || -L "$STABLE_APP_DIR" ]] \
  || fatal_gate "the laptop-staged stable directory is absent"
[[ -e "$STABLE_APP" || -L "$STABLE_APP" ]] \
  || fatal_gate "the laptop-staged app is absent"
[[ -e "$STAGING_MANIFEST" || -L "$STAGING_MANIFEST" ]] \
  || fatal_gate "the laptop staging manifest is absent"
required_check "the staged manifest, exact SHA, app hashes, bundle, team, fingerprint, Hardened Runtime, and strict signature are exact" staged_app_manifest_is_exact
cp "$STAGING_MANIFEST" "$EVIDENCE_DIR/staged-app-manifest.json" \
  || fatal_gate "the verified staging manifest could not be retained with the evidence"
CREATED_STABLE_APP_DIR="$STABLE_APP_DIR"
STABLE_APP_MAY_EXIST=true
required_check "the stable probe runtime identity is exactly approved" signed_probe_identity_is_approved
"$LIVE_PROBE" list-sources --skip-window-query \
  | jq '{authorization,signing}' >"$TCC_BEFORE_FILE" \
  || fatal_gate "could not snapshot the signed probe's before-run TCC state"
if ! confirm "Invoke the approved-signed probe's Camera, Microphone, and Screen Recording permission requests now? macOS owns every prompt."; then
  fatal_gate "visible TCC authorization was not authorized"
fi
TCC_STATE_MAY_DIFFER=true
if "$LIVE_PROBE" authorize --json "$EVIDENCE_DIR/authorization-attempt.json" \
    >"$EVIDENCE_DIR/authorization.stdout.json" 2>"$EVIDENCE_DIR/authorization.stderr.txt"; then
  AUTHORIZATION_EXIT=0
else
  AUTHORIZATION_EXIT=$?
fi
note "The authorization command exited $AUTHORIZATION_EXIT; macOS may require you to finish toggles in System Settings."
if ! confirm "Open the Privacy & Security pane and the three primary Apple help pages before checking toggles?"; then
  fatal_gate "TCC settings review was not authorized"
fi
open "x-apple.systempreferences:com.apple.settings.PrivacySecurity.extension" >/dev/null 2>&1 \
  || warn "The convenience System Settings deep link (not documented by Apple) did not open; use the verified path below."
open_url "https://support.apple.com/guide/mac-help/control-access-to-your-camera-mchlf6d108da/mac"
open_url "https://support.apple.com/guide/mac-help/control-access-to-the-microphone-on-mac-mchla1b1e1fe/mac"
open_url "https://support.apple.com/guide/mac-help/control-access-to-screen-and-system-audio-recording-mchld6aa7d23/mac"
step "Apple-verified path: Apple menu → System Settings → Privacy & Security → Camera. Turn on Grab Rabbit Live Cadence Probe if listed."
step "Apple-verified path: Privacy & Security → Microphone. Turn on Grab Rabbit Live Cadence Probe."
step "Apple-verified path: Privacy & Security → Screen & System Audio Recording. Turn on Grab Rabbit Live Cadence Probe for screen and audio. Apple documents the + button here if the app must be added manually."
pause "Finish the visible macOS prompts/toggles, close any restart notice, then press Enter."
required_check "Camera, Microphone, and Screen & System Audio authorization are all granted" tcc_is_granted
required_check "the same exact selected camera remains present after TCC authorization" signed_camera_id_is_present
"$LIVE_PROBE" list-sources --skip-window-query \
  | jq '{authorization,signing}' >"$EVIDENCE_DIR/tcc-granted.json" \
  || fatal_gate "could not snapshot the granted TCC state"

stage "Select one real browser window and prepare three cases" 10
say "What and why: the privacy contract permits one exact SCWindow only. The probe never constructs a display filter. Your camera/window IDs remain shell variables and are never written to evidence or .env."
if ! confirm "Create and open the local non-secret browser-case page in your default browser?"; then
  fatal_gate "browser-case page creation was not authorized"
fi
BROWSER_CASES_FILE="$EVIDENCE_DIR/browser-cases.html"
printf '%s\n' '<!doctype html><meta charset="utf-8"><title>Grab Rabbit cadence cases</title><style>body{font:28px system-ui;margin:8vh;background:#fff;color:#111}button{font-size:22px;margin:8px;padding:12px}.box{margin-top:40px;height:50vh;background:linear-gradient(135deg,#369,#9cf);display:grid;place-items:center}.active{animation:pulse .6s infinite alternate}@keyframes pulse{to{filter:hue-rotate(160deg);transform:translateY(12px)}}</style><h1>Grab Rabbit browser cadence cases</h1><button onclick="setCase(&quot;static&quot;)">Static</button><button onclick="setCase(&quot;low&quot;)">Low change</button><button onclick="setCase(&quot;active&quot;)">Active</button><div id="box" class="box">Static</div><script>let timer;function setCase(mode){clearInterval(timer);box.className="box";box.textContent=mode;if(mode==="low")timer=setInterval(()=>box.textContent="Low change "+new Date().toLocaleTimeString(),1000);if(mode==="active")box.className="box active"}</script>' \
  >"$BROWSER_CASES_FILE" || fatal_gate "could not create the local browser-case page"
open "$BROWSER_CASES_FILE" >/dev/null 2>&1 || fatal_gate "the local browser-case page did not open"
BROWSER_CASE_MAY_BE_OPEN=true
step "Keep this one browser window open. The Static button makes it fully still; Low change updates once per second; Active animates continuously."
step "Do not select the desktop, a display, Screen Sharing, Finder, or a different browser window."
pause "Arrange the real browser window at the size you want to capture, then press Enter."
WINDOW_SOURCE_JSON=$("$LIVE_PROBE" list-sources) \
  || fatal_gate "the signed probe could not read the real-window inventory"
jq -r '.windows[] | "  Window \(.windowID): \(.applicationName) — \(.title) [\(.width)x\(.height)]"' \
  <<<"$WINDOW_SOURCE_JSON" || fatal_gate "the real-window inventory was not valid JSON"
ask WINDOW_ID "Paste the exact numeric Window ID for the browser-case window:"
required_check "the selected Window ID is a nonzero UInt32" window_id_is_valid_number
required_check "the exact selected SCWindow is still capturable" window_id_is_present
SELECTED_WINDOW_APP=$(jq -er --argjson window_id "$WINDOW_ID" \
  '.windows[] | select(.windowID == $window_id) | .applicationName' <<<"$WINDOW_SOURCE_JSON") \
  || fatal_gate "the selected window application name could not be read"
required_check "exact camera/window preflight passes and creates no output" exact_preflight_passes_without_output
ask CASES_READY "Type YES after clicking Static, Low change, and Active once and seeing each behavior:"
required_check "all three browser cases were visibly prepared" test "$CASES_READY" = "YES"
ok "Selected a real $SELECTED_WINDOW_APP window; its numeric ID remains only in this wizard process."

stage "Run the shape, pause, and physical-disconnect matrix" 35
say "What and why: this stage records both candidate clocks, both camera-only and exact-window PIP, all three canvas shapes, every browser cadence case, pause/resume, and exact-device disconnect. Every output path is new; every run is checked before proceeding."
for candidate in camera-driven fixed-clock; do
  for canvas in 16x9 9x16 square; do
    run_owned_record "camera-only-$candidate-$canvas" false \
      --camera-id "$CAMERA_ID" --candidate "$candidate" --canvas "$canvas" \
      --duration 12 --fps 30 --pause-at 4 --pause-duration 1 --microphone
  done
done
for browser_case in static low-change active; do
  say "In the selected browser window, click the '$browser_case' case button now."
  ask CASE_CONFIRMATION "Type YES when the '$browser_case' behavior is visibly running:"
  required_check "the human confirmed the $browser_case browser case" test "$CASE_CONFIRMATION" = "YES"
  for candidate in camera-driven fixed-clock; do
    for canvas in 16x9 9x16 square; do
      run_owned_record "browser-$browser_case-$candidate-$canvas" false \
        --camera-id "$CAMERA_ID" --window-id "$WINDOW_ID" \
        --candidate "$candidate" --canvas "$canvas" \
        --duration 12 --fps 30 --pause-at 4 --pause-duration 1 --system-audio --microphone
    done
  done
done
say "Set the selected browser window to Active for the two fail-closed disconnect runs."
ask DISCONNECT_CASE_READY "Type YES when Active is visibly running:"
required_check "the active browser case is ready for disconnect testing" test "$DISCONNECT_CASE_READY" = "YES"
run_disconnect_record camera-driven
run_disconnect_record fixed-clock
required_check "all 26 matrix/disconnect outputs are present" movie_count_is 26

stage "Sample CPU, GPU, ANE, power, and thermal pressure" 15
say "What and why: powermetrics needs administrator authorization that an agent must never see. You will type the password directly into sudo's own prompt. The wizard never reads, pipes, echoes, stores, or logs it."
say "Set the selected browser window to Active. One sudo powermetrics process will span a camera-driven run followed by a fixed-clock run."
ask POWER_CASE_READY "Type YES when Active is visibly running and you have the administrator password ready:"
required_check "the active performance case is ready" test "$POWER_CASE_READY" = "YES"
POWER_FILE="$EVIDENCE_DIR/powermetrics.txt"
POWER_DONE_FILE="$EVIDENCE_DIR/powermetrics.done"
PERF_ERROR_FILE="$EVIDENCE_DIR/performance-helper.error.txt"
[[ ! -e "$POWER_FILE" && ! -e "$POWER_DONE_FILE" && ! -e "$PERF_ERROR_FILE" ]] \
  || fatal_gate "refusing to overwrite powermetrics/performance-helper evidence"
if ! confirm "Start the two wizard-owned probe runs and invoke sudo powermetrics directly now?"; then
  fatal_gate "external powermetrics sampling was not authorized"
fi
(run_performance_pair) &
PERF_HELPER_PID=$!
WIZARD_OWNED_PIDS+=("$PERF_HELPER_PID")
if sudo powermetrics \
    --sample-rate 500 \
    --sample-count 140 \
    --buffer-size 1 \
    --samplers tasks,cpu_power,gpu_power,ane_power,thermal \
    --show-process-energy \
    --show-process-gpu \
    --show-usage-summary \
    >"$POWER_FILE"; then
  POWER_EXIT=0
else
  POWER_EXIT=$?
fi
if ! : >"$POWER_DONE_FILE"; then
  if owned_pid_is_running "$PERF_HELPER_PID"; then kill -INT "$PERF_HELPER_PID" >/dev/null 2>&1 || true; fi
  wait "$PERF_HELPER_PID" >/dev/null 2>&1 || true
  untrack_owned_pid "$PERF_HELPER_PID"
  fatal_gate "could not write the powermetrics completion marker"
fi
if wait "$PERF_HELPER_PID"; then PERF_EXIT=0; else PERF_EXIT=$?; fi
untrack_owned_pid "$PERF_HELPER_PID"
[[ "$POWER_EXIT" -eq 0 ]] || fatal_gate "sudo powermetrics exited $POWER_EXIT"
if [[ "$PERF_EXIT" -ne 0 ]]; then
  PERF_FAILURE=$(sed -n '1p' "$PERF_ERROR_FILE" 2>/dev/null || true)
  fatal_gate "the performance probe pair exited $PERF_EXIT${PERF_FAILURE:+: $PERF_FAILURE}"
fi
required_check "powermetrics produced non-empty external resource evidence" test -s "$POWER_FILE"
required_check "camera-driven performance output is playable and privacy-clean" \
  validate_live_run "$RUNS_DIR/power-camera-driven.mov" "$RUNS_DIR/power-camera-driven.metrics.json" "$RUNS_DIR/power-camera-driven.events.jsonl" false
required_check "fixed-clock performance output is playable and privacy-clean" \
  validate_live_run "$RUNS_DIR/power-fixed-clock.mov" "$RUNS_DIR/power-fixed-clock.metrics.json" "$RUNS_DIR/power-fixed-clock.events.jsonl" false
"$SCRIPT_DIR/bind-powermetrics.sh" \
  "$RUNS_DIR/power-camera-driven.metrics.json" "$POWER_FILE" "$EVIDENCE_DIR/power-camera-driven.binding.json" \
  || fatal_gate "could not bind camera-driven metrics to powermetrics evidence"
"$SCRIPT_DIR/bind-powermetrics.sh" \
  "$RUNS_DIR/power-fixed-clock.metrics.json" "$POWER_FILE" "$EVIDENCE_DIR/power-fixed-clock.binding.json" \
  || fatal_gate "could not bind fixed-clock metrics to powermetrics evidence"
required_check "both powermetrics bindings contain exact metric and sampler hashes" powermetrics_bindings_are_valid

stage "Verify evidence, restore state, and record Tim's verdict" 15
say "What and why: the gate is not complete until every artifact is playable and hash-bound, privacy stayed closed, only owned processes stopped, temporary TCC/app/camera/browser state is restored, and Tim records the visual clock verdict."
required_check "all 28 expected outputs are playable, monotonic, approved-signed, and privacy-clean" verify_all_outputs
required_check "every wizard-owned process has stopped" no_owned_process_is_live
required_check "protected CuaDriver PID 12083 and Screen Sharing PID 9243 are still live" protected_processes_are_live
if ! confirm "Open Privacy & Security so you can restore the prototype app's TCC toggles to the before snapshot?"; then
  fatal_gate "TCC restoration was not authorized"
fi
open "x-apple.systempreferences:com.apple.settings.PrivacySecurity.extension" >/dev/null 2>&1 \
  || warn "The convenience deep link did not open; use Apple menu → System Settings → Privacy & Security."
step "Use the same Apple-verified Camera, Microphone, and Screen & System Audio Recording panes. Return the prototype app's toggles to their before-run state shown next."
jq '.authorization' "$TCC_BEFORE_FILE" || fatal_gate "the before-run TCC snapshot is unreadable"
pause "Restore those toggles, then press Enter."
BEFORE_CAMERA=$(jq -er '.authorization.camera' "$TCC_BEFORE_FILE") \
  || fatal_gate "the before-run Camera TCC snapshot is unreadable"
BEFORE_MICROPHONE=$(jq -er '.authorization.microphone' "$TCC_BEFORE_FILE") \
  || fatal_gate "the before-run Microphone TCC snapshot is unreadable"
BEFORE_SCREEN=$(jq -er '.authorization.screenCapturePreflightGranted' "$TCC_BEFORE_FILE") \
  || fatal_gate "the before-run Screen Capture TCC snapshot is unreadable"
if [[ "$BEFORE_CAMERA" == "not-determined" || "$BEFORE_MICROPHONE" == "not-determined" || "$BEFORE_SCREEN" == "false" ]]; then
  if ! confirm "Reset only the prototype bundle's originally-unset TCC entries so the machine returns to the snapshot?"; then
    fatal_gate "exact prototype TCC restoration was declined"
  fi
  if [[ "$BEFORE_CAMERA" == "not-determined" ]]; then
    tccutil reset Camera "$BUNDLE_ID" || fatal_gate "Camera TCC reset failed for the prototype bundle"
  fi
  if [[ "$BEFORE_MICROPHONE" == "not-determined" ]]; then
    tccutil reset Microphone "$BUNDLE_ID" || fatal_gate "Microphone TCC reset failed for the prototype bundle"
  fi
  if [[ "$BEFORE_SCREEN" == "false" ]]; then
    tccutil reset ScreenCapture "$BUNDLE_ID" || fatal_gate "Screen Capture TCC reset failed for the prototype bundle"
  fi
fi
"$LIVE_PROBE" list-sources --skip-window-query \
  | jq '{authorization,signing}' >"$TCC_AFTER_FILE" \
  || fatal_gate "could not snapshot the restored TCC state"
required_check "Camera, Microphone, and Screen TCC state matches the before snapshot" tcc_matches_snapshot
TCC_STATE_MAY_DIFFER=false
if ! confirm "Move the two manifest-verified staged artifacts to Trash and remove their helper-created parent only if it is then empty?"; then
  fatal_gate "stable app-path restoration was declined"
fi
osascript -e "tell application \"Finder\" to delete POSIX file \"$STABLE_APP\"" >/dev/null \
  || fatal_gate "Finder could not move the verified staged probe to Trash"
osascript -e "tell application \"Finder\" to delete POSIX file \"$STAGING_MANIFEST\"" >/dev/null \
  || fatal_gate "Finder could not move the verified staging manifest to Trash"
required_check "the verified staged app no longer occupies the stable path" test ! -e "$STABLE_APP"
required_check "the verified staging manifest no longer occupies the stable path" test ! -e "$STAGING_MANIFEST"
STABLE_APP_MAY_EXIST=false
if [[ -n "$CREATED_STABLE_APP_DIR" ]]; then
  [[ "$PROTOTYPE_ROOT" == /* ]] || fatal_gate "the prototype root is no longer an absolute path"
  [[ "$STABLE_APP_DIR" == "$PROTOTYPE_ROOT/.build/human-gate-stable" ]] \
    || fatal_gate "the stable app directory no longer equals the exact wizard-owned prototype path"
  [[ "$CREATED_STABLE_APP_DIR" == "$STABLE_APP_DIR" ]] \
    || fatal_gate "refusing to remove a directory other than the exact manifest-verified helper-created directory"
  [[ ! -e "$STABLE_APP" && ! -L "$STABLE_APP" ]] \
    || fatal_gate "refusing to remove the recorded directory before the stable app is gone"
  [[ ! -e "$STAGING_MANIFEST" && ! -L "$STAGING_MANIFEST" ]] \
    || fatal_gate "refusing to remove the recorded directory before the staging manifest is gone"
  stable_app_directory_is_empty "$CREATED_STABLE_APP_DIR" \
    || fatal_gate "the recorded wizard-created stable app directory is not empty"
  rmdir "$CREATED_STABLE_APP_DIR" \
    || fatal_gate "the recorded empty wizard-created stable app directory could not be restored"
  CREATED_STABLE_APP_DIR=""
fi
if [[ "$CAMERA_WAS_PRESENT_INITIALLY" == false ]]; then
  say "The selected camera was absent from the initial snapshot, so disconnect it to restore exact physical state."
  if ! confirm "Physically disconnect only the selected camera now?"; then
    fatal_gate "selected-camera restoration was declined"
  fi
  pause "Disconnect it and wait for camera discovery to update, then press Enter."
  required_check "the wizard-added exact camera is no longer present" selected_camera_is_absent
fi
required_check "the exact camera inventory matches the before-run snapshot" camera_inventory_matches_initial
CAMERA_STATE_MAY_DIFFER=false
say "Close the generated browser-case tab/window. No browser automation or preference change was made."
ask BROWSER_RESTORED "Type YES when the generated browser-case page is closed:"
required_check "the generated browser page was closed by the human" test "$BROWSER_RESTORED" = "YES"
BROWSER_CASE_MAY_BE_OPEN=false
osascript -e 'get volume settings' >"$EVIDENCE_DIR/volume-after.txt" \
  || fatal_gate "could not snapshot final audio volume/mute state"
pmset -g custom >"$EVIDENCE_DIR/power-after.txt" \
  || fatal_gate "could not snapshot final power preferences"
required_check "audio volume/mute state matches the before snapshot" cmp -s "$VOLUME_BEFORE_FILE" "$EVIDENCE_DIR/volume-after.txt"
required_check "power preferences match the before snapshot" cmp -s "$POWER_BEFORE_FILE" "$EVIDENCE_DIR/power-after.txt"
ps -p 12083,9243 -o pid=,comm=,etime= >"$EVIDENCE_DIR/protected-after.txt" \
  || fatal_gate "could not snapshot the protected processes after the run"
if ! confirm "Open the evidence movies so Tim can compare camera-driven and fixed-clock motion/resource feel?"; then
  fatal_gate "visual adjudication was not authorized"
fi
open "$RUNS_DIR" >/dev/null 2>&1 || warn "Could not open Finder; inspect $RUNS_DIR manually."
step "In QuickTime Player, compare matched camera-driven/fixed-clock files for camera fluidity over Static, Low change, and Active pages; watch pause/resume and all three shapes."
step "Use the JSON metrics and powermetrics evidence for cadence, latency, drift, drops, CPU/GPU/ANE, and thermal differences."
ask VERDICT "Enter exactly camera-driven, fixed-clock, or unresolved:"
required_check "Tim entered one permitted visual/runtime verdict" verdict_is_valid
ask VERDICT_REASON "Enter a concise non-secret reason for the verdict:"
[[ -n "$VERDICT_REASON" ]] || fatal_gate "a verdict reason is required"
if ! confirm "Write Tim's non-secret verdict and the final hash-bound manifest now?"; then
  fatal_gate "verdict/manifest write was not authorized"
fi
VERDICT_RECORDED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ) || fatal_gate "could not timestamp Tim's verdict"
jq -n --arg verdict "$VERDICT" --arg reason "$VERDICT_REASON" --arg recorded_at "$VERDICT_RECORDED_AT" \
  '{verdict:$verdict,reason:$reason,recorded_at:$recorded_at}' >"$EVIDENCE_DIR/verdict.json" \
  || fatal_gate "could not write Tim's verdict"
[[ "$VERDICT" != "unresolved" ]] || manual "Tim must resolve the camera-driven versus fixed-clock tradeoff after reviewing the captured evidence"
HOST_NAME=$(scutil --get ComputerName) || fatal_gate "could not read the Mini computer name"
MANIFEST_GENERATED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ) || fatal_gate "could not timestamp the final manifest"
jq -n \
  --arg schema "grab-rabbit-render-cadence-human-gate-v1" \
  --arg branch "$EXPECTED_BRANCH" \
  --arg commit "$RUN_SHA" \
  --arg generated_at "$MANIFEST_GENERATED_AT" \
  --arg host "$HOST_NAME" \
  --arg camera_name "$SELECTED_CAMERA_NAME" \
  --arg camera_type "$SELECTED_CAMERA_TYPE" \
  --arg window_app "$SELECTED_WINDOW_APP" \
  --arg verdict "$VERDICT" \
  '{schema:$schema,branch:$branch,commit:$commit,generated_at:$generated_at,host:$host,selected_sources:{camera_name:$camera_name,camera_type:$camera_type,window_application:$window_app,exact_ids_persisted:false},coverage:{stages:6,expected_movies:28,candidates:["camera-driven","fixed-clock"],canvases:["16x9","9x16","square"],browser_cases:["static","low-change","active"],pause_resume:true,physical_disconnect:true,powermetrics:true},privacy:{sentinel_required_zero:true,display_fallback_allowed:false},state_restored:true,protected_pids:[12083,9243],verdict:$verdict}' \
  >"$EVIDENCE_DIR/manifest.json" || fatal_gate "could not write the final evidence manifest"
required_check "the exact camera identifier does not appear anywhere in final evidence" camera_identifier_is_not_persisted
required_check "no camera/window identifier field or command argument appears in final evidence" identifier_fields_are_not_persisted
required_check "the verdict reason contains neither exact selected identifier" verdict_reason_has_no_exact_identifier
unset CAMERA_ID WINDOW_ID INITIAL_SOURCE_JSON SOURCE_JSON WINDOW_SOURCE_JSON
(cd "$EVIDENCE_DIR" \
  && find . -type f ! -name SHA256SUMS -print0 | sort -z | xargs -0 shasum -a 256 >SHA256SUMS) \
  || fatal_gate "could not write the final evidence hashes"
required_check "every final evidence hash verifies" evidence_hashes_verify
required_check "the checkout remains clean and bound to the original pushed SHA" checkout_remains_bound
ok "Evidence is complete at $EVIDENCE_DIR. No camera/window ID or password was persisted."

finish
